### ISSUE TITLE
大哥， 关于 a.config 配置文档的说明有吗？

### ISSUE THREAD

**Issue by Desmond-Liu** [AskyEdu/Asky#2]
大哥， 关于 a.config 配置文档的说明有吗？
貌似 wiki 里也没有啊

**Comment by Desmond-Liu** [comment]
btw, 源码呢？

**Comment by AskyEduAdmin** [comment]
@Desmond-Liu a.config一个简单json文件，不需要配置文档，参考教程中的Config.cs写法即可，

Asky工具类库本身的源码，过一段时间整理好代码和注释后，会开源，请放心
